### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by aduccig** [artiebits/pdf-to-printer#107]
The docs are saying that to fit the print in the page size, you have to do this:
`const options = {
  printer: "Zebra",
  unix: ["-n 2"],
  win32: ['-print-settings "2x"']
};`

But this actually prints the same page two times.

To fit the page the settings should be:
`const options = {
  printer: "Zebra",
  unix: ["-o fit-to-page"],
  win32: ['-print-settings "fit"']
};`

**Comment by artiebits** [comment]
hi @aduccig thank you! do you mind opening a PR with a fix? 😉

**Comment by artiebits** [comment]
Solved with #109
