### ISSUE TITLE
gsprint in addition to SumatraPDF

### ISSUE THREAD

**Issue by ccarnivore** [artiebits/pdf-to-printer#110]
I'd like to use gsprint as alternative to sumatrapdf.

I think the main reason why you've chosen sumatrapdf is the portable executable. 
But in my eyes sumatrapdf is not a good pdf-printing tool. 

What do you think when adding an ENV_Parameter to configure pdf-to-printer to use gsprint (installer won't be included) over sumatra?

If its okay for you, I'd start working on this and opening a PR when I'm   @#done.
@artiebits

**Comment by artiebits** [comment]
hi @ccarnivore, sorry for the delay in response. I really appreciate your contribution to the project but I don't think this task has the highest priority. I see more ppl struggling with using `pdf-to-printer` in [electron-vue ](https://github.com/artiebits/pdf-to-printer/issues/40) and [electron-react](https://github.com/artiebits/pdf-to-printer/issues/99) apps. So, if you are interested in contributing more to this project, then solving these issues is very important  😄
