### ISSUE TITLE
Output of getDefaultPrinter contains leading space character

### ISSUE THREAD

**Issue by steffanschlein** [artiebits/pdf-to-printer#119]
The output of `getDefaultPrinter` on Unix Systems contains a leading space character because of an off-by-one error in [the parsing code](https://github.com/artiebits/pdf-to-printer/blob/master/src/unix/printers.js#L16). The output on Windows is correct.

**Comment by artiebits** [comment]
Thank you Steffan.

**Comment by steffanschlein** [comment]
You are welcome.
