### ISSUE TITLE
Breaking change in non major version increase: list is not a function

### ISSUE THREAD

**Issue by wartab** [artiebits/pdf-to-printer#123]
**Describe the bug**
Version 1.4.0 introduced a breaking change of renaming a public API method list to getPrinters.

Minor version jumps should not introduce breaking changes. Please revert this release and bump the major version to 2.0.0.

**Comment by artiebits** [comment]
Hi Vincent, thank you for your feedback 👍

**Comment by wartab** [comment]
I corrected it in the OP, but the breaking change was introduced in 1.4, not 1.3.

**Comment by wartab** [comment]
I assume closing this without any reaction means that you don't care?

**Comment by wartab** [comment]
Taking that as a yes. Successfully migrated away from this library.
