### ISSUE TITLE
Angular 6 - ERROR in ./node_modules/pdf-to-printer/dist/bundle.js

### ISSUE THREAD

**Issue by santoshprakash** [artiebits/pdf-to-printer#127]
ERROR in ./node_modules/pdf-to-printer/dist/bundle.js
Module not found: Error: Can't resolve 'child_process' in 'D:\MyWorkPlace\set-fusion\social-document-service\frontend\node_modules\pdf-to-printer\dist'
ERROR in ./node_modules/pdf-to-printer/dist/bundle.js

My code  - 
import ptp from "pdf-to-printer";

ptp
  .print("assets/file.pdf")
  .then(console.log)
  .catch(console.error);
    
  }

**Comment by artiebits** [comment]
Hi @santoshprakash. Thanks for reporting your issue. Can I take a look at your app plz? I have a feeling you using "pdf-to-printer" in a browser application.

**Comment by santoshprakash** [comment]
yes In using "pdf-to-printer": "^1.4.0",
is this valid or I have to use something else, plz help

**Comment by artiebits** [comment]
this package is for node.js applications, you have to find another solution

**Comment by artiebits** [comment]
this package is for node.js applications. unfortunately, you need to find another solution. i am closing this issue because it' not actual anymore.
