### ISSUE TITLE
win32 settings didn't work

### ISSUE THREAD

**Issue by zhanghong0603** [artiebits/pdf-to-printer#137]
**Describe the bug**
I want to pop up the Print dialog , thie options are defined as follows, but it It didn't work.
let options = {
      'win32': ['-print-dialog', '-print-settings "2x"']
    }
    ptp.print(filePath, options).then((res) => {
      console.log('print res:', res)
    }).catch((err) => {
      console.error('print err:', err)
    });

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fxh615** [comment]
have you got the solutions ?

**Comment by zhanghong0603** [comment]
not yet,do you have a solution?

**Comment by zhanghong0603** [comment]
> have you got the solutions ?

not yet, do you have a solution ?
