### ISSUE TITLE
Print process fails when a printer name is given .

### ISSUE THREAD

**Issue by screwdycrow** [artiebits/pdf-to-printer#139]
**Describe the bug**
When I am trying to print to a any specific printer name (using the -print-to arguement), that exist and is installed in my system, the childprocess fials. However using the exact same command that was generated, directly through cmd, it works as expected.

**To Reproduce**
1. add a specific printer name to the printer options
2. try to print a document

**Expected behavior**
Expected result was to print the document using the printer that was provided

**Desktop (please complete the following information):**
 - OS: Windows 10 
- NodeJS v12.16.2

**Additional context**

i have tried to add the printer name in the options like this 

```javascript
    print(options) {
        const printer = this.settings.printer || 'default';
        if (printer === 'default') {
            ptp.getDefaultPrinter()
                .then(printerResp => {
                    return Promise.resolve({
                        ...options,
                        printer: printerResp
                    })
                })
                .then(options => {
                    ptp.print(this.path, options)
                })
                .catch(console.error);
        } else {
            ptp.print(this.path, {
                ...options,
                printer: printer
            })
                .catch(console.error);
        }
    }
```
in this function i am checking if the name of the given printer is explicitely "default" in this case i am using the `getDefautlfPrinter` method and then i am using its response as the printer name. The response always gives the name of the Default printer as expected, and then `print` works just fine. 

However if I give an explicit printer name to the option as it it seems on the second part of the conditional, i get the following error

(I am omiting the full path to the module and the input pdf file, for the shake of clarity)
```
Error: Command failed: C:\...\pdf-to-printer\dist\SumatraPDF.exe -print-to LEXLUTHOR -print-settings "fit,paper=A5" -silent C:\...\123print.pdf

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\...\\pdf-to-printer\\dist\\SumatraPDF.exe -print-to LEXLUTHOR -print-settings "fit,paper=A5" -silent C:\\...\123print.pdf'
}
```
**the generated command.**

`'C:\\...\\pdf-to-printer\\dist\\SumatraPDF.exe -print-to LEXLUTHOR -print-settings "fit,paper=A5" -silent C:\\...\\123print.pdf`

If I copy the command and paste directly into cmd, and execute it from there it works as expected.

This might be some problem with my system as well, since I haven't seen this issue here. It might even have to do with SumtraPdf.  However any guidance on what might cause this would be very helpful

**Comment by artiebits** [comment]
hi Dimitris, I will investigate your issue this weekend. Sorry about that!
