### ISSUE TITLE
 illegible characters show when printer named in other than the English character

### ISSUE THREAD

**Issue by peter-ay** [artiebits/pdf-to-printer#148]
printer's name are not displayed properly ,cause the print functional run to fail.

**Comment by artiebits** [comment]
Hi @peter-ay, which version of pdf-to-printer do you use? What is your OS? Could you provide me steps to reproduce the issue please?

**Comment by peter-ay** [comment]
Hi @artiebits  the version is : "pdf-to-printer": "^1.4.0" ,OS : Win7 64-bit ,
In my case, I use "getPrinters()" function to get my computer's printers list, as long as the printers named  by other that English character, will causes not only display wrong but "print()" function run to fail
Here is my screenshot for you reference, However ,all works well as long as you renamed them only  contain English character.
!
![UFUFZXGWTGDEN9 4%CR$4$2](https://user-images.githubusercontent.com/30825213/83088050-47b0ec00-a0c5-11ea-98d4-f79ae63d0e11.png)
