### ISSUE TITLE
Setting Copies in the Win32 Options Array is ignored.

### ISSUE THREAD

**Issue by lordkerwin** [artiebits/pdf-to-printer#161]
So, i set the options for win32 to 3 copies, as thats what i need.

```
const options = {
        printer: printer_name,
        win32: ['-print-settings "3x"']
    };
```
And then i do the print...
```
ptp.print(filePath, options).then(res => {
        console.log('Print Complete');
    }).catch(err => {
        console.log(err);
    });
```

But i still only ever get 1 copy sent to my printer.. Am i doing something wrong?

**Comment by artiebits** [comment]
Hi Sean. Sorry for the delay in response. The way you pass options looks correct to me. It makes me think it might be a problem of SumatraPDF v3.0.0 that we use to print PDF in Windows. I see they release v3.2 recently, so we can update the version. Let me know if you are interested in opening open a PR.

**Comment by artiebits** [comment]
Hi Sean, I've published a beta version `pdf-to-printer@1.4.2-beta.0` where I updated SumatraPDF to version 3.2. But I don't have a windows machine anymore, could you help me to test it, please?

**Comment by aashutoshrathi** [comment]
@artiebits The normal single page thing was working till `1.4.1`.
I switched to `pdf-to-printer@1.4.2-beta.0` for testing and facing this.
![image](https://user-images.githubusercontent.com/21199234/88455959-7a921900-ce97-11ea-9101-719b64f573e9.png)

**Comment by artiebits** [comment]
@aashutoshrathi i will take a look again, thank you for testing it 👍

**Comment by artiebits** [comment]
hi guys. sorry for the delay but I have published `pdf-to-printer@1.5.1-beta.0` with these changes https://github.com/artiebits/pdf-to-printer/pull/193. hope it works and solves the issue

**Comment by artiebits** [comment]
@aashutoshrathi I have tried `1.4.2-beta.0` and there is, indeed, the error. Then I've tried `1.5.1-beta.0` and it didn't throw any error but I am not 100% sure it prints a PDF because I don't have a printer anymore. Could you test it for me, please? I would appreciate it very much.

**Comment by aashutoshrathi** [comment]
Yeah, will check this one.
cc: @mohitkyadav Take a look with our app if you find time

**Comment by artiebits** [comment]
hi guys, did you have a chance to test if the fix works?

**Comment by aashutoshrathi** [comment]
@artiebits I just checked, it works for n copies now.

**Comment by artiebits** [comment]
oh, glad to hear it. thanks a lot for helping me with this issue! I will publish a new version with this fix shortly

**Comment by artiebits** [comment]
I have released version `1.5.1` with the fix, assume this issue can be closed. thanks everyone!

**Comment by sebastianroming** [comment]
@artiebits Has the `win32` option been removed lately? I'm using `5.0.0` but can't find any reference for passing this to Sumatra. Or has it been replaced with a native option I can't find? I need a possibility to define `n` copies of a document. 

Thanks!

**Comment by artiebits** [comment]
hi @sebastianroming. I've refactored the `print` method but I forgot about number of copies. Sorry for that! 
We have an open issue for it https://github.com/artiebits/pdf-to-printer/issues/288. Feel free to work on it!
