### ISSUE TITLE
Return job ID when using on windows

### ISSUE THREAD

**Issue by brunogoossens** [artiebits/pdf-to-printer#174]
At the moment when using this module on mac, the job ID is returned together with the printer name. When using this on windows, nothing is returned. Is there a way to make this possible so we can monitor the print job?

**Comment by artiebits** [comment]
Hi Bruno, I am sorry but I don't have a Windows machine at the moment, so I can't test it. In pdf-to-printer I use SumatraPDF to print documents on Windows. I would suggest you to take a look at [docs](https://www.sumatrapdfreader.org/free-pdf-reader.html), maybe there are some arguments you can pass to SumatraPDF to return job ID. 
If it's possible then we can find a solution for pdf-to-printer.

**Comment by brunogoossens** [comment]
I don't see any option to return the job ID from SumatraPDF.
My solution at the moment is asking the printer for his job list and search for new jobs in this list.
