### ISSUE TITLE
Uncaught No such file

### ISSUE THREAD

**Issue by bharath2232** [artiebits/pdf-to-printer#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by artiebits** [comment]
Hi Bharat, thanks for reporting the issue. 

The utility will throw `No such file` error if the given PDF file does not exist in the file system. It means if you trying to print a PDF from URL it won't download the file for you. You can take a look at [this example ](https://github.com/artiebits/pdf-to-printer/tree/master/examples/express-server) to see how to download PDF files and use them with `print` method.

I hope it helps. If no then please provide me more details on how to reproduce the issue.

**Comment by artiebits** [comment]
hi @bharath2232, did you manage to solve your issue?

**Comment by bharath2232** [comment]
Hi @artiebits , Yes I Managed to solve it, but I a new issue, in dev it working fine, But in Production, it's Printing two time. Do you know any solution for it?

**Comment by artiebits** [comment]
@bharath2232 Did you check your printer settings? Do you use the same printer on dev and prod? 

Pdf-to-printer uses the printer setting from your machine so the problem might be there. Otherwise, I need to see the code or be able to test it.

Looking forward to hearing from you.

**Comment by artiebits** [comment]
hi @bharath2232 how it's going?
