### ISSUE TITLE
Type definitions for typescript

### ISSUE THREAD

**Issue by matyx** [artiebits/pdf-to-printer#189]
**Is your feature request related to a problem? Please describe.**
I cant use this library in TS, because there are missing type definitions (TS wont compile).

**Describe the solution you'd like**
Include types in github repo (I can send PR).

**Describe alternatives you've considered**

**Additional context**

**Comment by artiebits** [comment]
hi @matyx, 
Indeed, would be nice to have type definitions for TS. And I am happy to hear you can send a PR. 👍
