### ISSUE TITLE
Integrate with Vuejs using vue-cli-plugin-electron-builder

### ISSUE THREAD

**Issue by conorholgate** [artiebits/pdf-to-printer#192]
When using this plug in on a normal electron app, it works as intended.

When spinning up a vuejs app, along with the electron builder. I install pdf-to-printer plug in I get the below error

bundle.js?50d2:1 Uncaught Error: Platform not supported
    at eval (bundle.js?50d2:1)
    at Object.eval (bundle.js?50d2:1)
    at r (bundle.js?50d2:1)
    at eval (bundle.js?50d2:1)
    at eval (bundle.js?50d2:1)
    at eval (bundle.js?50d2:1)
    at Object.eval (bundle.js?50d2:1)
    at eval (bundle.js:2)
    at Object../node_modules/pdf-to-printer/dist/bundle.js (chunk-vendors.js:172)
    at __webpack_require__ (app.js:849)

I have looked high and low for a solution but not come across anything. 

Below are my dependencies

 "dependencies": {
    "pdf-to-printer": "^1.5.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-service": "~4.5.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  }

Please let me know if you need any more information.

**Comment by thetractor** [comment]
@conorholgate how did you fix this issue?

**Comment by conorholgate** [comment]
I THINK it ended up being how i imported the plugin into my project

This is how i imported it into my background.js >> const ptp = require("pdf-to-printer").

I also created a vue.config.js file in the root of the project, which included the below:

module.exports = {
    configureWebpack: {
        devtool: 'source-map'
    },
    pluginOptions: {
      electronBuilder: {
        nodeIntegration: true,
        externals: ["pdf-to-printer"],
        nodeModulesPath: ['node_modules']
      }
    }
  }

Let me know if this sorts it

**Comment by thetractor** [comment]
Thanx @conorholgate this seems to fix the error above but now I get a `No such file` error from the click event of my button

```javascript
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <HelloWorld msg="Welcome to Your Vue.js App" />
    <button @click="printPDF">Print</button>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";
import ptp from "pdf-to-printer";

export default {
  name: "Home",
  components: {
    HelloWorld
  },
  methods: {
    printPDF() {
      ptp
        .print("../assets/sample.pdf")
        .then(console.log)
        .catch(console.error);
    }
  }
};
</script>
```
![image](https://user-images.githubusercontent.com/22886611/101787196-1ba80600-3aff-11eb-8c95-62c819d5bafa.png)

**Comment by conorholgate** [comment]
Try putting the pdf in the Public folder. Does this print?

I found that this worked fine in development mode. As soon as I built the .exe, I had the same issue of "No such file"

I think electron bundles the public and asset folders up so there aren't accessible(please don't quote me on this, i haven't used electron that many times). Below is how i managed to get it working.

I chose to save the PDF in the temp folder of the application.

```
<template>
  <div id="app">
    <button @click="saveFile">Save File</button>
    <br>
    <br>
    <button @click="printToBrother">Print To Brother</button>
    <button @click="printToTattoo">Print to Tattoo</button>
  </div>
</template>

<script>
import { remote, ipcRenderer } from 'electron';
import { type } from 'os';
import { log } from 'console';
const ptp = require("pdf-to-printer")
const path = require('path')
const fs = require('fs')
const axios = require('axios');

export default {
  name: 'App',
  methods: {
    printToBrother() {
      const passDesign = path.join(remote.app.getPath('temp'), '/SamplePass.pdf') 
        ptp.print(passDesign).catch(error => {
        console.log(error);
      })
      console.log("sent");
    },
    printToTattoo() {
      const options = {
        printer: 'Evolis Tattoo Rewrite'
      }
      const passDesign = path.join(remote.app.getPath('temp'), '/SamplePass.pdf') 
        ptp.print(passDesign, options).catch(error => {
        console.log(error);
      })
      console.log("sent");
    },
    
  }
}
</script>
```

references:
https://nodejs.org/api/path.html#path_path_join_paths
https://stackoverflow.com/questions/47957479/how-to-use-electrons-app-getpath-to-store-data
