### ISSUE TITLE
win10 electron print failure

### ISSUE THREAD

**Issue by ckrgithub** [artiebits/pdf-to-printer#194]
Error: spawn cmd.exe ENOENT
   at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:80)

**Comment by ckrgithub** [comment]
use your github demo no problem,but not mine .
my demo: npm install --save pdf-to-printer.
I donot know why

**Comment by conorholgate** [comment]
I am getting a similar issue. i am using Vue js with a electron builder.

Imported ptp in the background.js: 
"const ptp = require("pdf-to-printer")"

Created a function:
ptp.print("SamplePass.pdf").catch(error => {
    console.log(error);
  })

this pdf is in the root of the program (also tried with the pdf in the C drive, same error)

If i use electron on its own. it works fine.


Error: spawn C:\FILEPATH\dist_electron\SumatraPDF.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',

**Comment by ckrgithub** [comment]
![image](https://user-images.githubusercontent.com/18225851/96265296-d6cc8b00-0ff7-11eb-8c8a-00123ccace90.png)

This problem may be caused by this reason：
my demo file is relative path, yours is absolute path

**Comment by artiebits** [comment]
hi @ckrgithub thank you for investigating the issue.
seems to me we need to fix this line https://github.com/artiebits/pdf-to-printer/blob/master/src/win32/print.js#L13. but, unfortunately, I don't have any experience with electron. could you help me with this issue?

**Comment by ckrgithub** [comment]
@artiebits @conorholgate  In webpack.config.js add this code and it works
`
node: {
    __dirname: true
  }
`

**Comment by ckrgithub** [comment]
There are no problems in development, not in production.
**Error: spawn node_modules\pdf-to-printer\dist\SumatraPDF.exe ENOENT**

**Comment by conorholgate** [comment]
I managed to get this working in development mode by adding the Sumatra.exe into the dist_electron folder. However, when building the electron app, it fails to load.

I am assuming, it is not bundling the exe into the build, thus not loading.

**Comment by 1134506391** [comment]
> 

how did you solve it in the end

**Comment by conorholgate** [comment]
I think I used electron-download-manager to firstly download the PDF which saved it in my temp folder. Then it allows you to print the pass

**Comment by 1134506391** [comment]
> 

thank you
