### ISSUE TITLE
print() fails when there is a space in the path from which the script is run

### ISSUE THREAD

**Issue by anuraagvaidya** [artiebits/pdf-to-printer#20]
Hey,

`.print()` fails when there is a space in the path when using on Windows OS.

```
Error: Command failed: C:\Anuraag\<path with space>\node_modules\pdf-to-printer\dist\SumatraPDF.exe -print-to-default -silent assets/temp.pdf
'<path with space comes here>' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Socket.<anonymous> (internal/child_process.js:405:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Anuraag\\' +
    '<path with space>\\node_modules\\pdf-to-printer\\dist\\SumatraPDF.exe ' +
    '-print-to-default -silent assets/temp.pdf'
```

**To Reproduce**
1) Create a directory with spaces on it on Windows 10 OS
2) Store a PDF in an "assets" folder
3) Copy commands from the readme.

**Expected behavior**
Path should be placed in quotes when sending to PDF engine

**Desktop (please complete the following information):**
 - OS: Windows 10
- NodeJS v12

**Comment by artiebits** [comment]
Hi Anuraag,

Thank you for reporting, will be fixed ASAP.

**Comment by artiebits** [comment]
@anuraagvaidya, a beta version `1.0.1-beta.0` with a fix from @khannanova has been published. You can do `npm install --save pdf-to-printer@1.0.1-beta.0` to check if it works. I have tried it on a Windows machine, seems to work fine. Please let me know if it helps you so I can merge it to master.
 
Looking forward to hearing from you.

**Comment by brandonsay95** [comment]
I can verify that this resolved my issue with spaces in the path

**Comment by artiebits** [comment]
@anuraagvaidya I am closing the issue since it seems to be fixed.
