### ISSUE TITLE
-print-settings "paper=statement"  not work

### ISSUE THREAD

**Issue by ckrgithub** [artiebits/pdf-to-printer#214]
not consistent with Chrome
![image](https://user-images.githubusercontent.com/18225851/98336480-fd537400-2041-11eb-9412-fc52d88a24fa.png)

![image](https://user-images.githubusercontent.com/18225851/98336956-cf226400-2042-11eb-8f09-9c0619c8de71.png)

**Comment by artiebits** [comment]
did you try to use this setting with SumatraPDF v3.2? does it work?

**Comment by ckrgithub** [comment]
@artiebits I just tried it. None of it worked

**Comment by artiebits** [comment]
then I have a feeling it is the problem of SumatraPDF v3.2
