### ISSUE TITLE
Can't include pdf-to-printer library when executing electron after packaging with electron-packager

### ISSUE THREAD

**Issue by indalaterre** [artiebits/pdf-to-printer#215]
Hello, seems that after the build with electron-packager, the app can't find the module of pdf-to-printer.
Attached there is a screenshot of the error 

![image](https://user-images.githubusercontent.com/20315786/99825276-1df9ee80-2b57-11eb-9e4c-85c1bacdae4a.png)

**Comment by artiebits** [comment]
hi @indalaterre. sorry for the late response. what version of pdf-to-printer do you use?
