### ISSUE TITLE
It's print both side of page, but i need single side of page.

### ISSUE THREAD

**Issue by nurul-islam01** [artiebits/pdf-to-printer#218]
How can i set single side print of a page? i change my printer driver setting that's ok one side print. but pdf-to-printer have no setting single side or double side print.
Please help me.

**Comment by artiebits** [comment]
hi @nurul-islam01,

did you try

**Comment by artiebits** [comment]
hi @nurul-islam01,

did you try something like this?

```javascript
import ptp from 'pdf-to-printer';

const options  = {
  win32: ['-view "single page"']
};

ptp
  .print('assets/pdf-sample.pdf')
  .then(console.log)
  .catch(console.error);
```

We use SumatraPDF to print documents on Windows, so you can take a look at [this page](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html) for all available options

**Comment by artiebits** [comment]
@nurul-islam01 did you have a chance to check if it helps?

**Comment by nurul-islam01** [comment]
> @nurul-islam01 did you have a chance to check if it helps?

**Comment by nurul-islam01** [comment]
> @nurul-islam01 did you have a chance to check if it helps?

Error: Command failed: C:\inetpub\wwwroot\printer.backend\node_modules\pdf-to-printer\dist\SumatraPDF.exe -print-to-default -view "single page" -silent F:/PrinterServer/webPrintingQueue/1011219001_Nurul_Islam.pdf

    at ChildProcess.exithandler (node:child_process:309:12)
    at ChildProcess.emit (node:events:329:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\inetpub\\wwwroot\\printer.backend\\node_modules\\pdf-to-printer\\dist\\SumatraPDF.exe -print-to-default -view "single page" -silent F:/PrinterServer/webPrintingQueue/1011219001_Nurul_Islam.pdf'
}

**Comment by mcdado** [comment]
I think you need this option:

```js
win32: [
    '-print-settings "simplex"'
]
```
