### ISSUE TITLE
Add human readable name to the list returned by getPrinters

### ISSUE THREAD

**Issue by ferretwithaberet** [artiebits/pdf-to-printer#220]
**Is your feature request related to a problem? Please describe.**
We only have the printer code name, with `_`, which is not nice for displaying.

**Describe the solution you'd like**
Electron's `getPrinters` returns a list of objects representing printers which got properties for `name`(device code) and a `displayName` which contains the human readable name of the printer without `_`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by artiebits** [comment]
Hi @ferretwithaberet. Thanks for reporting the issue, I will take a look.

**Comment by artiebits** [comment]
Hi @ferretwithaberet. Sorry it took so long but I don't have a printer at home. And since I am still working remotely I can't investigate this issue.

**Comment by ferretwithaberet** [comment]
> Hi @ferretwithaberet. Sorry it took so long but I don't have a printer at home. And since I am still working remotely I can't investigate this issue. 

If you have a linux machine, there existins `cups-pdf` which simulates a printer which saves the printed documents as pdf files. You do not have to be sorry thought, take your time.

**Comment by ferretwithaberet** [comment]
Fixed by #235, #242 and #243.

**Comment by ferretwithaberet** [comment]
Closing since issue was fixed, now it only needs to be released with the next version of the package.

**Comment by artiebits** [comment]
i have published version 2.0.0 with your fixes. thank you for the contribution!
