### ISSUE TITLE
Printer name with space in it errors

### ISSUE THREAD

**Issue by davidsyoung** [artiebits/pdf-to-printer#222]
**Describe the bug**
On windows platform, when there is a printer with a space in it's name, and you pass a printer, the command fails to run as it's not escaped with quotes.

**To Reproduce**
1. Rename printer with a space in it
2. Pass that printer name as returned by getPrinters()
3. Command that is produced doesn't run as there's a space.

**Expected behavior**
The printer name to be escaped with quotes on the commandline. I believe this is a similar error to the path of the file to print.

I know this isn't your main focus, but would be greatly appreciated fix. Thank you!

**Comment by artiebits** [comment]
Hi @davidsyoung, I have published `pdf-to-printer@1.7.0` with a fix from @mcdado which should solve your issue. Could you check if it helps, please?
