### ISSUE TITLE
SLOW printing time 3-4 minutes

### ISSUE THREAD

**Issue by zizzi-dev** [artiebits/pdf-to-printer#223]
On Windows Server 2016 i'm using this module and i saw on node_modules SumatraPDF.exe is used versione 3.0.0 i had slow performances printing PDF. I updated the sumatraPDF.exe file to versione 3.1.2 inside node modules and solved the issue!
Hope you can update the sumatraPDF.exe file inside your dependencies !

Cheers !

**Comment by artiebits** [comment]
Hi @zizzi-dev,

Thanks for reporting the issue, I appreciate it! 

I am pretty sure that SumatraPDF was updated to version 3.2 https://github.com/artiebits/pdf-to-printer/releases/tag/v1.5.1. What version of pdf-to-printer do you use?
