### ISSUE TITLE
Cannot be called after wrapping with electron

### ISSUE THREAD

**Issue by deadline1997** [artiebits/pdf-to-printer#224]
Sorry, I don't know English very well, so I am Posting the code snippet

`
   SumatraPDF.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

Then I changed the path code on the 'electron-util.js'
`
export const fixPathForAsarUnpack = (path) => {
  // return isUsingAsar ? path.replace("app.asar", "app.asar.unpacked") : path;
  return path.replace("/app.asar", "")
};
`

And then the print worked

**Comment by LFdeWeb** [comment]
问题解决了吗  我也遇到点问题  打印的位置不是从顶部开始的。

**Comment by deadline1997** [comment]
我的已经解决了, 打印位置这个我没有遇到

**Comment by tushar0911** [comment]
Hi 
I am also having same error could you post the complete solution to it.
