### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Brunni** [artiebits/pdf-to-printer#225]
Hi,
this project is licensed under MIT, but SumatraPDF executable is part of the repository with is GPLv3 as far as I can see.
How is this working out?

What do I need to do, when I want to use this package in a commercial electron shell application?

Best
Michael

**Comment by artiebits** [comment]
Hi Michael! It's a good question. But it's better to ask SumatraPDF team how you can use it. 
I would appreciate it if you share with me their answer.
