### ISSUE TITLE
Print cut into stripes

### ISSUE THREAD

**Issue by denyncrawford** [artiebits/pdf-to-printer#230]
**Describe the bug**
The printe comes out cut into stripes, I don't know if it's a problem with my pdf or if I'm doing something wrong.

**To Reproduce**

1. Print a PDF like in the documentation example.

**Expected behavior**
Print a nice document.

**Screenshots**

This is how it prints the document:

![image](https://user-images.githubusercontent.com/28849055/109204306-f2088d80-7783-11eb-90f0-71b2b0d29b44.png)

And this is a basic print from crhome, it is what it should be:

![image](https://user-images.githubusercontent.com/28849055/109204391-09477b00-7784-11eb-98ad-2ddce1e1651f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Node 15.2.0
 - Version 1.7.0

**Comment by denyncrawford** [comment]
I have been investigating a little and it seems that it is a problem that sumatra has from 3.1 and it happens in several models of printers, apparently if you downgrade to 3.0 it works.

**Comment by denyncrawford** [comment]
I downgraded the binary to 3.0 and now it works, but I don't know how it affects pdf-to-printer. I also need to install my application on multiple machines and I shouldn't have to do this manually, maybe with gulp ... but could you include a method to choose the version of sumatra?

**Comment by artiebits** [comment]
Hi Miguel, thank you for opening the issue and investigating it. I don't think it's a good idea to store both SumatraPDF version 3.0 and 3.2 because it will make the npm package size bigger. But I've published a version `pdf-to-printer@1.6.0-sumatra-pdf-v3.0` with Sumatra PDF v3.0. Let me know if it solves your issue

**Comment by denyncrawford** [comment]
Thanks a lot, I'll be testing it later, but anyway, in terms of module size , wouldn't it be more efficient to fetch and unzip sumatra in the build? I mean right after installation.
