### ISSUE TITLE
Printing cut-off pages ('fit-to-page' print setting not working - using default Windows 10 print settings)

### ISSUE THREAD

**Issue by tenzint** [artiebits/pdf-to-printer#233]
**Describe the bug**
Unable to format the print. The print does not have "fit-to-page" settings. It has the Windows 10 default print settings that cuts off part of the page.

**To Reproduce**
1. Install `pdf-to-printer`, write the script written in the documentation: 
```
 const options = {
  printer: "Zebra",
  unix: ["-o fit-to-page"],
  win32: ['-print-settings "fit"']
};

ptp
  .print("assets/pdf-sample.pdf", options)
  .then(console.log)
  .catch(console.error);
```
2. Run the script

**Expected behavior**
You want to print the PDF file with print-settings set to "fit-to-page"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: v89
 - Printer: HP Printer, I think. I do not have SumatraPDF installed on the computer.

**Additional context**
Does "pdf-to-printer" npm package use SumatraPDF in the background? You are using this in the documentation. Do I have to download SumatraPDF for this npm package to work? I expect not to download anything else. Windows 10 printer does not need any software to download PDF so.... Please instruct me if I need to download SumatraPDF separately

**Comment by tenzint** [comment]
I am currently changing the actual printer's default print settings to make it fit to page.

**Comment by ferretwithaberet** [comment]
The package ships with a  `SumatraPDF` executable. This might be an issue with `SumatraPDF`, needs more investigation.

**Comment by tenzint** [comment]
Thank you for clarifying. So SumatraPDF is not working for me then.
