### ISSUE TITLE
My printer does not have toner, so printing status is not returning here.

### ISSUE THREAD

**Issue by mitulsrv** [artiebits/pdf-to-printer#237]
**Describe the bug**
The problem is when i send print command to printer, the printer does not have enough page or toner to print then any error or printer status is not returning here.

**To Reproduce**
1. Go to 'Send printer command with using pdf-to-printer package in electron.'
2. Printer does not have enough page or toner to print.
3. Showing empty status in then block

**Expected behavior**
Behavior as returning exception message from printer related to hardware or some problems or status of printer
Like Paper is not there. please add papers.

**Desktop (please complete the following information):**
 - OS: Windows 10

** Needed proper exception status from printer, like status of printer.

**Comment by ferretwithaberet** [comment]
I was looking into how to make the `Promise` returned by `ptp.print()` to resolve only after the whole printing process finishes but it seems that `pdf-to-printer` only queues printing jobs(at least on linux through `lp`). I am still searching for a way to make it work, when I find out how(if I will) this issue will probably be fixed too.
