### ISSUE TITLE
Printer's name charset error

### ISSUE THREAD

**Issue by dtboy1995** [artiebits/pdf-to-printer#240]
**Code**
```js
const ptp = require('pdf-to-printer')
ptp
    .getPrinters()
    .then(console.log)
    .catch(console.error);
```
**Screenshots**
![image](https://user-images.githubusercontent.com/19227547/114335675-d57fb380-9b7f-11eb-94b4-ff367cb85cbd.png)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Nodejs
 - Version 12

**Comment by ferretwithaberet** [comment]
Can you open a command prompt and provide the output of `wmic printer get default,deviceid,name`?

**Comment by dtboy1995** [comment]
Sorry to reply so late


![image](https://user-images.githubusercontent.com/19227547/115651675-38323580-a35e-11eb-838d-dfa9c5ed7264.png)

**Comment by ferretwithaberet** [comment]
> @ferretwithaberet sorry to reply so late
> 
> ![image](https://user-images.githubusercontent.com/19227547/115651675-38323580-a35e-11eb-838d-dfa9c5ed7264.png)

It would be great if you could copy that output and paste it here, so I can test with your exact printer names.

**Comment by dtboy1995** [comment]
> > @ferretwithaberet sorry to reply so late
> > ![image](https://user-images.githubusercontent.com/19227547/115651675-38323580-a35e-11eb-838d-dfa9c5ed7264.png)
> 
> It would be great if you could copy that output and paste it here, so I can test with your exact printer names.

```
Default  DeviceID                                  Name
FALSE    导出为WPS PDF                             导出为WPS PDF
FALSE    发送至 OneNote 16                         发送至 OneNote 16
FALSE    TOSHIBA e-STUDIO306-07893269              TOSHIBA e-STUDIO306-07893269
FALSE    OneNote for Windows 10                    OneNote for Windows 10
FALSE    NPIE6926F (HP Color LaserJet CP5225dn)    NPIE6926F (HP Color LaserJet CP5225dn)
FALSE    NPI04050A (HP LaserJet 400 color M451dn)  NPI04050A (HP LaserJet 400 color M451dn)
FALSE    Microsoft XPS Document Writer             Microsoft XPS Document Writer
FALSE    Microsoft Print to PDF                    Microsoft Print to PDF
FALSE    Fax                                       Fax
TRUE     Deli DL-888D(NEW) (副本 2)                Deli DL-888D(NEW) (副本 2)
FALSE    Deli DL-888D(NEW) (副本 1)                Deli DL-888D(NEW) (副本 1)
FALSE    Deli DL-888D(NEW)                         Deli DL-888D(NEW)
```

thanks

**Comment by ferretwithaberet** [comment]
It seems to work on linux(had to add the `_` to the device id because you cannot have spaces in the device id on Linux) I tried node versions 15, 14, 12 and it worked on all of them. I will test it on windows soon too.

![image](https://user-images.githubusercontent.com/46427158/115701385-67ea3900-a370-11eb-95ad-83ced8d4d29b.png)

**Comment by dtboy1995** [comment]
Windows cmd / powershell default charset not uft-8

**Comment by ferretwithaberet** [comment]
> Windows cmd / powershell default charset not uft-8

Yeah, I documented myself a bit, seems like we will need to use `chcp` somehow to change the charset to UTF-8 before we parse it.

**Comment by dtboy1995** [comment]
maybe use [iconv-lite](https://www.npmjs.com/package/iconv-lite)..

**Comment by gaolingxiao** [comment]
Same problem here.
