### ISSUE TITLE
Printer listing fails on macOS

### ISSUE THREAD

**Issue by joernroeder** [artiebits/pdf-to-printer#25]
Printer listing fails on macOS 10.12 and the child process exits with the following error.
Ti seems like `lpstat` uses different arguments.

```
Error: Command failed: lpstat -e
[1] lpstat: Error - unknown option “e”.
```

**Comment by artiebits** [comment]
HI @joernroeder, thank you very much for reporting the issue. I will take a look at it today later, but feel free to open a PR if you want to!

**Comment by artiebits** [comment]
@joernroeder can you try `pdf-to-printer@1.0.3-beta.0` with the fix from @khannanova, please?

**Comment by joernroeder** [comment]
@artiebits yes, #26 looks good to me. thanks @khannanova!

**Comment by artiebits** [comment]
I am closing the issue then. Thank you all for contributing to the project!
