### ISSUE TITLE
PTP incorrectly working with PM2 

### ISSUE THREAD

**Issue by eriskhan** [artiebits/pdf-to-printer#252]
**Describe the bug**
PTP works incorrectly with PM2. Not really that of a problem with PTP, but it'd be great if you could dive in and check what's wrong.

All in all: if we start a script containing
```
ptp
.print("...")
```
with, say, `node index.js`, everything works flawlessly. However, with PM2 PTP doesn't set printing tasks and doesn't throw any errors.  
**To Reproduce**
1. Clone the repository: https://github.com/eriskhan/barcode-printing.
2. Put the printer deviceid in .env
3. Start a pm2 process: `pm2 start --name index node index.js`
3. Try to open: http://localhost:61010/333/John/28.04/Example/Example/birka.html
4. See error (although there are no errors, we can see it's not setting a printer task.
5. Stop a pm2 process and repeat everything after starting `node index.js`. Everything works flawlessly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Additional context**
I'm not sure that the problem is certainly with PTP or PM2: it may be my fault, however I don't see any. Thanks for your help in advance :)

**Comment by sebastianjung** [comment]
Actually i'm facing a similar problem.

running my script with pm2 start index.js leaves out all the network printers when using `getPrinters()`. 

When using `node index.js` i get all network printers with the same method (getPrinters())

**Comment by artiebits** [comment]
thank you for reporting the issue guys, I will investigate it 👍🏻

**Comment by ferretwithaberet** [comment]
[This](https://stackoverflow.com/questions/50543004/pm2-app-gets-permission-denied-when-printing) might be related.

**Comment by eriskhan** [comment]
Also important to notice: I’ve tried running pm2 as an administrator and as a user. Nothing worked for me
