### ISSUE TITLE
Print multiple files at once in one print job

### ISSUE THREAD

**Issue by PatricioNG** [artiebits/pdf-to-printer#264]
**Is your feature request related to a problem? Please describe.**
This may exist already, but is there a way to specify an array of file names or a comma separated list of file names to be sent together in one print job? Sending a file one by one causes stress on the printer from starting and stopping print jobs.

**Describe the solution you'd like**
Something like
```
ptp.printBatch( //String Array )....
```

**Describe alternatives you've considered**
Not sure if this exists already, but didn't seem like it did.

**Comment by KirstLMCG** [comment]
You can assign the array of files to a variable and call forEach on that array then print each PDF in one print job. Here is an example:
```
const pdfs = ["example1.pdf", "example2.pdf];

pdfs.forEach((pdf) => {
  ptp.print(pdf, options)
});
```

**Comment by ferretwithaberet** [comment]
> You can assign the array of files to a variable and call forEach on that array then print each PDF in one print job. Here is an example:
> 
> ```
> const pdfs = ["example1.pdf", "example2.pdf];
> 
> pdfs.forEach((pdf) => {
>   ptp.print(pdf, options)
> });
> ```

This assign a print job for each file. They explicitly said
> to be sent together in one print job

because 

> Sending a file one by one causes stress on the printer from starting and stopping print jobs

I can see the utility of this and it should not be that hard to implement(at least for linux).

**Comment by KirstLMCG** [comment]
I have used my approach already that I suggested and it prints all documents in one print job.
