### ISSUE TITLE
Considering either a beta or a minor release

### ISSUE THREAD

**Issue by joshycube** [artiebits/pdf-to-printer#265]
Few PR's have been merged recently. Although it is possible to use a Github link to a certain branch in the package.json it would be great to use the main packag with a new version or a beta tag.

**Comment by artiebits** [comment]
Hi. Sorry I forgot to release a new version with your changes before going on vacation

**Comment by artiebits** [comment]
And indeed I don’t add new features simply because I developed on this project during my free time but have other interests now. However I try to support every contribution to this project and answer questions

**Comment by joshycube** [comment]
@artiebits I really appreciate your answer and 100% respect for looking after this library.
I am happy to help and raise some PRs - I do have some other bugs which I might be able PR in.

**Comment by artiebits** [comment]
It would be awesome. Thanks in advance!
