### ISSUE TITLE
Wrong printing orientation

### ISSUE THREAD

**Issue by isakovicq** [artiebits/pdf-to-printer#267]
Entire process goes fine, but no matter what orientation I provide, content is printed with portrait orientation. Any suggestion on how to fix this?

**Comment by ferretwithaberet** [comment]
I do not know of any particular part of `pdf-to-printer` which would do this. Can you also provide which platform you are on (Windows/Linux/macOS), the printer model, the literal code you used (If it is possible)? I will not necessarily try to fix this issue, but providing this information will increase the chances of us finding the problem.

**Comment by isakovicq** [comment]
Sorry for not providing that earlier, platform is Windows 10, I can't specify one printer since it will be for wide use, trying to automate some processes and this will be running on multiple printers. Part of code that is handling printing is here:

This is how print settings look:
-print-settings "landscape, fit, 3x" -print-to "PRT_KIQL1" -exit-on-print

```
    printerWatcher.on("create", function (file, stats) {
        const cartonDirectory = utils.categoryType(CARTON_PRINTERS,printer.printing_directory);
        const labelInformation = utils.parseFileInformation(utils.getFileName(file));

        utils.logMessage(`${utils.getFileName(file)} is added to ${printer.printing_directory}`)
        const ready = handlePrinters(cartonDirectory, labelInformation, file);

        if(ready) {
            const settings = `-print-settings "${printer.orientation}, fit, ${parseInt(labelInformation.numberOfCopies)}x" -print-to 
            "${printer.printer_name}" -exit-on-print`;
            const printOptions = [];
            printOptions.push(settings);
            const options = {
              win32: printOptions
            };

            ptp
            .print(file, options)
            .then(()=>{
                archivePrintedFiles(file)
            })
            .catch((error)=>{
                utils.logMessage(`Printing failed. Label to be printed: ${utils.getFileName(file)} - Error log: ${error}.`)
            });
        }
    });
```

**Comment by isakovicq** [comment]
Fixed it was not related to this library.
