### ISSUE TITLE
When to know each job is currently being printed?

### ISSUE THREAD

**Issue by KirstLMCG** [artiebits/pdf-to-printer#268]
Hi, not sure if there is a way to know when to find out when each job is currently printing? So I can say something like this?

```
    pdfDocs.forEach((pdf, index) => {
      ptp
        .print(pdf.path, options(pdf.tray))
        .then(console.log)
        .catch(console.error, "err");
      setText(`Printing pack ${index + 1} of ${pdfDocs.length}`);
    });
  };
```

**Comment by ferretwithaberet** [comment]
> Hi, not sure if there is a way to know when to find out when each job is currently printing? So I can say something like this?
> 
> ```
>     pdfDocs.forEach((pdf, index) => {
>       ptp
>         .print(pdf.path, options(pdf.tray))
>         .then(console.log)
>         .catch(console.error, "err");
>       setText(`Printing pack ${index + 1} of ${pdfDocs.length}`);
>     });
>   };
> ```
This will be solved when #261 will be properly implemented. At the moment pdf-to-printer only queues the printing jobs so you have to monitorize them yourself.

**Comment by KirstLMCG** [comment]
@artiebits I can't find the place where I can see the example to download the PDF, do you know where it is?

**Comment by artiebits** [comment]
hi @KirstLMCG this package is not responsible for downloading PDF, only printing it. But you can do something like this to download a PDF, print it, and then delete it.

```javascript
const fs = require("fs");
const path = require("path");
const printer = require("pdf-to-printer");
const fetch = require("node-fetch");

function print(request, response) {
  function onSuccess() {
    response.send({ status: "completed" });
  }

  function onError(error) {
    response.send({ status: "error", error });
  }

  // Download a PDF
  fetch(request.query.url)
    .then((res) => res.buffer())
    .then((buffer) => {
      // Save it
      const pdf = save(buffer);


      // Print it
      printer
        .print(pdf)
        .then(onSuccess)
        .catch(onError)
        // Delete it
        .finally(() => remove(pdf));
    });
}

function save(buffer) {
  const pdfPath = path.join(__dirname, randomString() + ".pdf");
  fs.writeFileSync(pdfPath, buffer, "binary");
  return pdfPath;
}

function remove(pdf) {
  fs.unlinkSync(pdf);
}

function randomString() {
  return Math.random().toString(36).substring(7);
}

module.exports = print;
```

**Comment by KirstLMCG** [comment]
oo okay, amazing, thank you :)

**Comment by artiebits** [comment]
I am closing this issue because the requested functionality is implemented  in the latest version of pdf-to-printer. But that works for Unix-like systems only
