### ISSUE TITLE
Paper format/slize in numeric value, is it possible?

### ISSUE THREAD

**Issue by isakovicq** [artiebits/pdf-to-printer#276]
**Is your feature request related to a problem? Please describe.**
Hi, I was wondering is it possible to provide format/slize of the paper in numeric value, like for example I want it to be 55x35mm?

**Describe the solution you'd like**
I would like to provide those numeric values to printer, since it requires that size in order to show label I am printing properly.

**Comment by artiebits** [comment]
Hi @isakovicq you can find all available options here https://www.sumatrapdfreader.org/docs/Command-line-arguments for Windows, or here https://www.computerhope.com/unix/ulp.htm if you are using pdf-to-printer on Unix-like OS

**Comment by artiebits** [comment]
Hi guys. Supported page sizes are  `A2`, `A3`, `A4`, `A5`, `A6`, `letter`, `legal`, `tabloid`, `statement`, so I am not sure if you can add custom sizes, but check the [SumatraPDF docs](https://www.sumatrapdfreader.org/docs/SumatraPDF-documentation) and please, let me know if it's possible or not. Then I can update the readme

**Comment by GitHubRulesOK** [comment]
You can add paperkinds in Windows Forms and if the printer respects them you can use say A4LeftHalf but your on your own for how thats done in Windows System and which printer will accept that as paperkind. So you can define a media output as `55x35mm` but you need to then check if the printer  driver lists that as an acceptable page name or number, It is not down to SumatraPDF it is down to you checking out Windows Printing support for that driver custom settings.
