### ISSUE TITLE
Platform not supported error in linux

### ISSUE THREAD

**Issue by alpfreda** [artiebits/pdf-to-printer#287]
**Platform not supported** occurred in **v5.0.0** when running code on linux

![](https://media.discordapp.net/attachments/866214716745842748/905404564470124554/Screen_Shot_2021-11-03_at_1.33.49_PM.png)

But its work perfectly in the **v3.0.0** 

big thanks

**Comment by artiebits** [comment]
Hi @alpfreda, the package no longer supports Linux and other Unix-like operating systems, the functionality moved to a new package https://github.com/artiebits/unix-print.
You can check the release notes https://github.com/artiebits/pdf-to-printer/releases/tag/v4.0.0.
Sorry for the inconvenience!

**Comment by alpfreda** [comment]
@artiebits Thanks for your reply.
Our customers used the app on both platforms (linux & win)
what are your suggestions?

**Comment by artiebits** [comment]
i guess something like this

```javascript
import os from "os";
import { print as printForWindows } from 'pdf-to-printer'; 
import { print as printForLinux } from 'unix-print'; 

export default function print(file, options) {
  if (os.platform() === "win32") {
    printForWindows("file.png", options);
  } else {
    printForLinux("file.png", options);
  }
}
```

**Comment by alpfreda** [comment]
thanks.
