### ISSUE TITLE
getPrinters giving Fax as a printing option

### ISSUE THREAD

**Issue by HabibulHH** [artiebits/pdf-to-printer#289]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by artiebits** [comment]
Hi @HabibulHH I don't think it's an issue, because If you go to the printer settings in Windows you will see that fax.

**Comment by GitHubRulesOK** [comment]
A Facsimile Printer or Printer with an integrated modem, or Modem with an integrated image printer
Is always a FAX printer, just like any other one.
