### ISSUE TITLE
Not printing pdf when I am using windows build version of Electron . I am using electron builder

### ISSUE THREAD

**Issue by HabibulHH** [artiebits/pdf-to-printer#290]
Uncaught (in promise) Error: spawn \SumatraPDF.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:77)

**Comment by m4heshd** [comment]
Probably because the executable could be inside the packaged `asar` archive. You can't spawn any native processes from inside the `asar` file. You have to unpack the whole `pdf-to-printer` module for it to work. Try the following property in `electron-builder` configuration.

```json
"asarUnpack": [
    "**/node_modules/pdf-to-printer/**/*"
]
```
