### ISSUE TITLE
How to handle multiple operating systems?

### ISSUE THREAD

**Issue by Patrick-Remy** [artiebits/pdf-to-printer#291]
**Describe the bug**
I try to support both unix-like and windows printers, and require both `unix-printer` package and this package. I abstracted those libraries in a custom service, that checks the current platform. Unfortunately it fails in runtime, as you throw an error on unsupported platforms. Instead it would be nicer to only throw in case of method call

**Additional context**
```
App threw an error during load
Error: Platform not supported
    at /node_modules/pdf-to-printer/dist/bundle.js:1:4221
    at /node_modules/pdf-to-printer/dist/bundle.js:1:4267
    at /monitor/node_modules/pdf-to-printer/dist/bundle.js:1:84
```

**Comment by artiebits** [comment]
ah, good catch!

**Comment by artiebits** [comment]
done #296
