### ISSUE TITLE
Change Printer interface

### ISSUE THREAD

**Issue by artiebits** [artiebits/pdf-to-printer#297]
To be consistent with [unix-print](https://github.com/artiebits/unix-print) package, refactor: 

```typescript
interface Printer {
  deviceId: string;
  name: string;
}
```

to

```typescript
interface Printer {
  printer: string;
  description: string | null;
}
```

**Comment by aakash1003** [comment]
@artiebits can you explain the issue ?

**Comment by artiebits** [comment]
Hi @aakash1003! Some people want to make printing app that works on both Windows and Unix-like Operating systems 
(check [this discussion](https://github.com/artiebits/pdf-to-printer/issues/287#issuecomment-958897137)). One of the solutions would be to create a wrapper function like this:

```typescript
import os from "os";
import { getDefaultPrinter as getDefaultPrinterWindows } from "pdf-to-printer";
import { getDefaultPrinter as getDefaultPrinterUnix } from "unix-print";

export default function getDefaultPrinter(): Printer {
  if (os.platform() === "win32") {
    getDefaultPrinterWindows(file, optionsForWindows);
  } else {
    getDefaultPrinterUnix(file, optionsForUnix);
  }
}
```

However, `getDefaultPrinterWindows` and `getDefaultPrinterUnix` return different format of data. So, we need to make it consistent. 

I hope I explained the issue well. If you have any further questions, please don't hesitate to ask!

**Comment by artiebits** [comment]
@aakash1003 let me know if you are interested in implementing the changes, otherwise maybe someone else would like to do contribute

**Comment by artiebits** [comment]
i decided to close this issue, because I have doubts on how to name the fields of Printer object
