### ISSUE TITLE
add paperkind at  printing option

### ISSUE THREAD

**Issue by hxdyj** [artiebits/pdf-to-printer#303]
Sumatra PDF pageSize only support A2, A3, A4, A5, A6, letter, legal, tabloid, statement.
But I need to set paper size to B5 JIS.

at Sumatra PDF new version. It add -paperkind=${num} printing option.

https://www.sumatrapdfreader.org/docs/Version-history [ 3.3 (2021-07-06) ]

https://github.com/sumatrapdfreader/sumatrapdf/issues/1812

**Comment by artiebits** [comment]
hi @hxdyj could you provide more details about the feature you requesting? I would like to know:
- A clear and concise description of what the problem is. 
- A clear and concise description of what you want to happen.

**Comment by hxdyj** [comment]
> Hii @hxdyj could you please provide more details about the feature you requesting? Because I didn't understand it. Would be nice to have:
> 
> * A clear and concise description of what the problem is.
> * A clear and concise description of what you want to happen.
> 
> Thanks!

Thank for your reply ! I am update the issue.

**Comment by artiebits** [comment]
hi @hxdyj thanks for providing more details! I have a question tho, did you try `paperSize: 'B5 JIS'`? I know that documentation doesn't mention it, but I have a feeling that should work

**Comment by artiebits** [comment]
@hxdyj please let me know if it works

**Comment by hxdyj** [comment]
@artiebits I am sorry. I don't know it work or not. Just find official website changelog add this.

**Comment by artiebits** [comment]
no problem at all! It would be nice if you try `paperSize: 'B5 JIS'` and let me know if it works. I can't try myself because I don't have a printer anymore.

**Comment by hxdyj** [comment]
> no problem at all! It would be nice if you try `paperSize: 'B5 JIS'` and let me know if it works. I can't try myself because I don't have a printer anymore.

I'am try to this param at printer.  this param need printer support input pagesize, In other words, need printer set the tray pagesize correct, then paperkind will be works.
