### ISSUE TITLE
How to get selected printer list of supported page size?

### ISSUE THREAD

**Issue by hxdyj** [artiebits/pdf-to-printer#304]
How to get selected printer list of supported page size? 
like 
``` ts
function getSupportPaperSizes(printerName:string){
//...
   return ['A4','B5']
}
```

https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-devicecapabilitiesa   DC_PAPERSIZE
window has c++ function to get this.

**Comment by matteofranceschini** [comment]
Uhh that would be lovely. I don't think this has been implemented, yet.

**Comment by hxdyj** [comment]
I am allreay complete self.

**Comment by hxdyj** [comment]
@matteofranceschini I am allreay complete self.

**Comment by matteofranceschini** [comment]
how did you manage to solve this issue? I'm interested, too! :)

**Comment by hxdyj** [comment]
@matteofranceschini 
1. I am use edge-js, 
2. write c# code get supported pagesize and trays and others. 
3. output c# code to dll.
4. edge-js can be call dll's defineded functions.
