### ISSUE TITLE
Blank file printed when printDialog is false on zebra printers

### ISSUE THREAD

**Issue by Dellsmell** [artiebits/pdf-to-printer#333]
**Describe the bug**
When printing to a Zebra printer [zt510, zt410], while the print dialog parameter is false, the file will be printed as a blank page.

**To Reproduce**

1. Set a zebra printer as your default printer.
2. Attempt to print file using pdf-to-printer.
3. A blank page will be printed.

**Expected behavior**
Expected pdf-to-printer to print the file selected in code.

**Example Code**

`async function testPrint1() {
    print('test.pdf').then(console.log).catch((error) => {console.error(error)})
}`

`async function testPrint2() {
    var options = {
        printDialog: false,
        paperSize: "A6",
        scale: "fit"
    }
    print('test.pdf', options).then(console.log)
}`

**Comment by artiebits** [comment]
Hi @Dellsmell. Sorry for the delay in response. Unfortunately, I don't have a Zebra printer anymore, so I can't investigate the issue :/. 
I am not sure tho if the issue with this package or with SumatraPDF that it uses to print docs.

**Comment by Dellsmell** [comment]
@artiebits  Thanks for the reply. I was able to fix the issue by changing the way I format my PDF documents.

There is no proper page size for a 4x6 label, and A6 is the closest at 4-1/8 x 5-7/8 in. When generating my documents, I was passing the page size 4x6, which causes content to overflow on the page and, for some reason, causes the paper to print blank.

Reducing the actual document size fixed the issue.

**Comment by artiebits** [comment]
good to know that your issue is solved! I will close it then :)
