### ISSUE TITLE
Print works in development but not production

### ISSUE THREAD

**Issue by muhammadkaleem57** [artiebits/pdf-to-printer#341]
I am developing a React-Electron application where I am using this package to print pdf files which works for development but not for the production exe file.

 const filePath = `${app.getPath('documents')}\\test\\test.pdf`
const options = {
                     printer: printerName,
                      paperSize: 'A4',
                      silent : false,
                      printDialog: false,
                      copies: 1,
}
 print(filePath, options).then((response) => {
     log.info(`Print ${type} Completed`)
     this.removeFile(fileName)
 })

This works perfectly in development. But when I create an exe using electron forge. After the installation of exe file everything is working fine except print function not even throws any exception. Please suggest something

**Comment by artiebits** [comment]
@muhammadkaleem57 please take a look at this PR https://github.com/artiebits/pdf-to-printer/pull/258, probably `sumatraPdfPath` option is what you need
