### ISSUE TITLE
ValidPaperSize

### ISSUE THREAD

**Issue by demobiel** [artiebits/pdf-to-printer#345]
**Is your feature request related to a problem? Please describe.**
We are wondering why the valid paper size are hardcoded as a constant? We are printing on label printers, and it looks "foolish" to fork this repo only because of this.

**Describe the solution you'd like**
Being able to define custom paper sizes

**Describe alternatives you've considered**
Forking :)

**Comment by artiebits** [comment]
Hi @demobiel, thank you for reporting the issue. There is another alternative that you might consider. Opening a pull request with an improvement, so other users of this package might benefit from your work!

**Comment by demobiel** [comment]
I would honestly just not check if the paper size is valid and let the developer who implements your library be responsible for providing a valid paper size. There are libraries available that allows you to check for this.
As you are able to name the paper sizes how you want on a printer, it is really hard to know which paper sizes are available on a printer.

So I see two options:
- implement a request to the printer to get the available paper sizes, but this is hard to implement for each operating system
- remove the check on line 147 of /print/print.ts, or just check that it is a string

I would go for option 2, as there are many libraries for each OS that allows you to request available paper sizes from your printer.

Kind regards, and have a nice weekend!

Andries
