### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by joaosn** [artiebits/pdf-to-printer#352]
I have this problem

in function exec()
error: Command failed: .\SumatraPDF.exe -print-to-default -silent D:\impress\jvffzyzz.pdf

in print-to-pdf
{ Error: Command failed: D:\jv\node_modules\pdf-to-printer\dist\SumatraPDF.exe -print-to-default -silent D:\impress\sfajv.pdf

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'D:\\jv\\node_modules\\pdf-to-printer\\dist\\SumatraPDF.exe -print-to-default -silent D:\\impress\\sfajv.pdf',
  stdout: '',
  stderr: '' }

but if I run via CMD the impression of success

would be something in SumatraPDF.exe
or on my pc would have some output

**Comment by artiebits** [comment]
Ola Joao! Are you sure that the path to the PDF is correct?

**Comment by JRBARROZ** [comment]
i m having the same issue with this lib, my pdf is correct.

**Comment by JRBARROZ** [comment]
node:child_process:397
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: C:\Users\jhona\Desktop\printer_no_pain_no_gain\node_modules\pdf-to-printer\dist\SumatraPDF.exe -print-to-default -silent Amazing.pdf

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\jhona\\Desktop\\printer_no_pain_no_gain\\node_modules\\pdf-to-printer\\dist\\SumatraPDF.exe -print-to-default -silent Amazing.pdf',
  stdout: '',
  stderr: ''
}

**Comment by JRBARROZ** [comment]
the error is different, when the file is not found

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No such file".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by joaosn** [comment]
yes my friend is right, my system actually generates the files dynamically, i even found an alternative in another lib, thanks for the attention

**Comment by joaosn** [comment]
I wish I had used this project, so I could send several PDFs without waiting time
https://github.com/joaosn/gerenciadorImpressaoJV/blob/master/main.js

**Comment by joaosn** [comment]
code is very simple at a glance main.js
Asim would work. I made an app in electron that keeps monitoring a folder, my web system downloads PDFs files in this folder directly, when this happens my app reads this folder and prints directly without confirmation

**Comment by GitHubRulesOK** [comment]
SumatraPDF will give some limited feedback if you follow the advice NEVER RUN SILENT until you have established the routing is static, the messages get discarded when you use -silent thus no way of telling what went wrong.
