### ISSUE TITLE
Can it achieve that the printed content is centered?

### ISSUE THREAD

**Issue by qigaibigbig** [artiebits/pdf-to-printer#353]
Can it achieve that the printed content is centered?like this
![image](https://user-images.githubusercontent.com/52882460/157180638-a763d7c7-ebf8-4826-8e5e-af03f1e82d53.png)

What I am currently printing out looks like this
![image](https://user-images.githubusercontent.com/52882460/157180782-65a49df1-9bb1-41ed-8f8b-b1ce4e247c22.png)

**Comment by artiebits** [comment]
Hi! This package uses SumatraPDF to print documents, so I suggest you to check its documentation https://www.sumatrapdfreader.org/docs/Command-line-arguments. If it's possible with SumatraPDF then we can make it work in this package too!

**Comment by qigaibigbig** [comment]
> 你好！这个包使用 SumatraPDF 来打印文档，所以我你查看它的文档https://www.sumatrapdfreader.org/docs/Command-line-arguments。可以使用 SumatraPDF，所以我们也可以建议在这个包中工作！

I think it should work, but I don't know how to use this package to debug

**Comment by GitHubRulesOK** [comment]
centering is not possible as the choice is determined by windows forms thus you over-ride the default (A4/Letter) with the printers output page e.g. 6x4 etc. and scale up or scale down (shrink or fit) for autofit and quality printing of PDF use acrobat, SumatraPDF is designed for GDI/GUI viewing and can send PDF to GUI print drivers that control layouts.
