### ISSUE TITLE
Remote PDF file support?

### ISSUE THREAD

**Issue by sctaix** [artiebits/pdf-to-printer#371]
Currently, this module support local PDF file only.

print("https://www.orimi.com/pdf-test.pdf").then(console.log);
>> returns "Uncaught (in promise) No such file"

Is there any plan for supporting PDF file from remote url?

**Comment by artiebits** [comment]
Hi @sctaix, no such plans. I explained here why I don't want to do it https://github.com/artiebits/pdf-to-printer/issues/257. I am closing this issue, but feel free to re-open it if you want to discuss it :)

have a nice weekend!
