### ISSUE TITLE
Slow printing, specially on first attempt

### ISSUE THREAD

**Issue by xjuanc** [artiebits/pdf-to-printer#383]
Hello everyone, 

I'm doing background (silent) printing for a POS app and it's usually super slow, specially the first time I print something, it takes a lot of time:

- Around ~10s at slow computers (friend's computers) 
- Around ~4s in my computer

After the first print is done, it usually takes much less but way too noticiable for my friends to be happy with it (around ~6s sometimes even more!, and around ~1.5s in my computer).

I've already checked that the slowness is not made by other aspects of the app, through logs I have found that the part taking most of the time for complete is the .print function (Around 80% of the time)

Have anyone else face this problem? Could this be a bug somehow I came through? 

Any solution or idea to fix this whatsoever? GREATLY appreciate any help to fix this.

Thanks a lot and hope everyone has a great day.

**Comment by augustosnk12** [comment]
I am facing the same here. Did you find anything?
