### ISSUE TITLE
Large PDF Size When Printing

### ISSUE THREAD

**Issue by Tieantono** [artiebits/pdf-to-printer#397]
**Is your feature request related to a problem? Please describe.**
I'm currently developing a printing server solution (web app) which will print a PDF file into network printers that connected to the server. I was planning to use this nice package for simplify the PDF printing process. However, I found that the PDF file that will be sent to the printer is quite large, despite the actual PDF file is about 100KB, and when I checked the printing status in Windows Spooler (See what's printing), it was around 100MB. I'm worry that this will become a performance issue.

**Describe the solution you'd like**
Is it possible to make the size of the document that will be sent to the printer smaller?

**Describe alternatives you've considered**
I have tried using Adobe Reader .exe through command line to execute a printing request, and the size of the document that will be sent to the printer is actually not large, using the same actual file size I've mentioned above, the final size is around 350KB.

**Additional context**
![image](https://user-images.githubusercontent.com/14927392/189978801-713f2618-24da-42c9-8140-d6d7ff24bf4f.png)
The top one was the result of Adobe Reader printing, while the bottom one is the result of using this package for printing

**Comment by artiebits** [comment]
Hi! It might be an issue with SumatraPDF that we use as a dependency to print files. I have bumped its version and published a beta version `pdf-to-printer@5.4.0-beta.0`. Could you please test it and let me know if it works?

**Comment by Tieantono** [comment]
> Hi! It might be an issue with SumatraPDF that we use as a dependency to print files. I have bumped its version and published a beta version `pdf-to-printer@5.4.0-beta.0`. Could you please test it and let me know if it works?

Hi, thank you for your update, but the issue still persists, I suppose SumatraPDF doesn't have any option to make the size smaller then?

**Comment by artiebits** [comment]
Hi @Tieantono, sorry for the delay in response. If it didn't help then I am afraid there is nothing I can do within this package to fix this issue. :(
