### ISSUE TITLE
Blank space at top of paper when printed

### ISSUE THREAD

**Issue by Qurishe** [artiebits/pdf-to-printer#398]
**Describe the bug**
@artiebits I get extra white space at the top of the paper (you can see it below in pictures) when using this library.
But when i printed the pdf using Microsoft Edge, the extra space was much less than the one printed with the library.

**To Reproduce**

1. Should print the pdf from the top.

**Expected behavior**
Currently the printed paper wastes a lot of white paper. There shouldbe a way to consume paper based on pdf size (height).

**Screenshots**
This one is printed with the library and there is a lot of blank space at the top.
![20220926_224830](https://user-images.githubusercontent.com/32069358/192355417-8e080273-5835-4e2a-af6f-f04c9d68d4aa.jpg)

The left one is printed using Microsoft Edge which has less blank space than before.
![20220926_224914](https://user-images.githubusercontent.com/32069358/192355609-28b8df49-860e-434b-b47b-5676dfc2b93b.jpg)

**Additional context**

**Comment by artiebits** [comment]
Hi! It might be an issue with SumatraPDF that we use as a dependency to print files. I have bumped its version and published a beta version `pdf-to-printer@5.4.0-beta.0`. Could you please test it and let me know if it works?

**Comment by Qurishe** [comment]
Thank you, I will test it and will let u know!

**Comment by Antonio0001999** [comment]
Did it work? I'm having the same issue and thougth it was related to configuration of scale when executing the print method, but the output doesn't change.

![Image 2022-10-03 at 19 30 56](https://user-images.githubusercontent.com/99355000/193641763-244416c4-2aee-47d2-a06c-3f1858e7d0da.jpeg)

**Comment by Qurishe** [comment]
Well, i had no luck, i haven't yet tested the beta which @artiebits fixed.
I tested another module called node-pdf-printer

**Comment by artiebits** [comment]
hi guys! I am closing this issue because If release v5.4.0 didn't help then I am afraid there is nothing I can do within this package because it uses SumatraPDF to print files
