### ISSUE TITLE
Not possible to print when printer is in black/white mode

### ISSUE THREAD

**Issue by Blume987** [artiebits/pdf-to-printer#41]
**Describe the bug**
I only have one black ink cartridge in the printer. What makes it impossible for me to print a black page. If I only allow black and white printing in the print settings, the print job cannot be started because the program wants to print in color.

**To Reproduce**
1. Remove the color ink from your printer.
2. Try to print a pdf with only black content.
3. You will get an empty sheet "printed".

**Expected behavior**
If i want to print a black page, the pinter should be able to print it without color ink

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Version [10.14.5]
 - Printer: [Canon IP2700]

**Comment by Blume987** [comment]
Just saw the pullrequest: #19 
Might be related and my issue would be fixed by adding an option like:
```
printer.print(pdf, {
    blackplot: true
});
```

**Comment by artiebits** [comment]
Hi @Blume987, thanks a lot for reporting the issue. Could you please try `lp filename` and `lp -o blackplot filename` and say me if the first command reproduces the issue and the second one solves it.

**Comment by Blume987** [comment]
Hi @artiebits , thanks four your help.
Unfortunately none of both commands work.
I'm not familiar enough with the lpr commands. But as it seems the printer tries to print with the color cartridge. Since it is empty and I only need black and white printouts at this printer, I don't want to insert a new color ink. Any ideas if there are other parameters or settings I could try to print only with the black ink?

**Comment by artiebits** [comment]
thank you for testing it, Ben! if `lp -o blackplot filename` doesn't work then passing `blackplot` option to `print` method won't help. 
Unfortunately, I am on a vacation for the next 2 weeks but I will try to find a printer with the black ink and find a solution asap.

**Comment by Blume987** [comment]
Thank you!
In the meantime I will get a color ink and try it again so we can be sure that the error is because of the missing color cartridge.

**Comment by Blume987** [comment]
Got a color cartridge and was able to print the black page. Sadly the page was printed in light gray.

**Comment by artiebits** [comment]
Hi @Blume987, sorry for the delay in response. I tested it on macOS 10.14 with a color cartridge and it works fine. I also tried to print on a Zebra printer which has a black ribbon. Works fine. 
So I think the issue not in the pdf-to-printer itself also because nobody else reports the same issue. 
Sorry, looks like I can do nothing here because I can't reproduce the issue.

**Comment by Blume987** [comment]
Thanks for looking into it.
Maybe it's the printer itself, or the driver. I've already tried different solutions, unfortunately without success. If I get something that works, I'll get back to you.

**Comment by artiebits** [comment]
Thank you!
