### ISSUE TITLE
Getting Error while sent document for print

### ISSUE THREAD

**Issue by ervijjusty** [artiebits/pdf-to-printer#42]
Hello, I'm using Electron and angular I'm saved my pdf in pdf dir but getting error when printing

zone.js:391 Error: Command failed: "C:\Users\\Desktop\\node_modules\electron\dist\resources\electron.asar\renderer\SumatraPDF.exe" -print-to "Zebra" -silent "C:\Users\\AppData\Roaming\/pdf/digi-50726_1568982692.pdf"
The system cannot find the path specified.

    at ChildProcess.exithandler (child_process.js:299)
    at ChildProcess.emit (events.js:182)
    at maybeClose (internal/child_process.js:962)
    at Socket.stream.socket.on (internal/child_process.js:381)
    at Socket.emit (events.js:182)
    at Pipe._handle.close (net.js:606)

**Comment by artiebits** [comment]
Hi @ervijjusty, thank you for reporting the issue. looks like it's related to  https://github.com/artiebits/pdf-to-printer/issues/40.
I am on a vacation for the next week, so don't expect me to replay soon. Sorry for this!

**Comment by ervijjusty** [comment]
@artiebits any update on this ??

**Comment by artiebits** [comment]
hi @ervijjusty, sorry for the delay in response. Do you have your code somewhere so I can clone it and investigate the issue?

**Comment by ervijjusty** [comment]
@artiebits  sorry for that but i cannot  share the code becoz of internal policy.
 if needed so let me know I'll create a demo project for you.

**Comment by artiebits** [comment]
@ervijjusty it would help, thank you!
