### ISSUE TITLE
Paper size required

### ISSUE THREAD

**Issue by vjose1903** [artiebits/pdf-to-printer#431]
Hello, sorry that the previous time I could not give you an answer, my pc was damaged and I could not continue with the project.

I would like to know if I could make the beta version again with the paper of 8.5 inches x 5.5 inches, so I can test it.

**Comment by artiebits** [comment]
that beta version actually was merged to master and published. so, check out the latest version of pdf-to-printer, I hope it helps

**Comment by vjose1903** [comment]
ok, I'll check this out

**Comment by artiebits** [comment]
ah, my bad. it's not merged to master yet. A beta version you can test is `5.4.1-beta.0`
Pass a name selectable from your printer settings to the `paperSize` optio

**Comment by vjose1903** [comment]
a selectable name for this paperSize is, half-letter or halfLetter

**Comment by artiebits** [comment]
> a selectable name for this paperSize is, half-letter or halfLetter

then specify that size. 

I am closing the issue because now you can pass any paper size as an option
