### ISSUE TITLE
Not working with 32 bit systems

### ISSUE THREAD

**Issue by fquer** [artiebits/pdf-to-printer#433]
Hi everyone,

This module is not working with 32 bit os. We can change sumatra with 32 bit version its working. Can you do implementation for 32 bit os ?

**Comment by artiebits** [comment]
hi @fquer 

thanks for reporting the issue. it was always supposed to work with win32. i made a mistake by copy-pasting SumatraPDF win64. I've published a new version `pdf-to-printer@5.5.0-beta.1`. let me know if it fixes your issue, then I will merge it and publish

**Comment by fquer** [comment]
hi @artiebits,
I tested on 32 bit os and its working fine. Thanks for fast response.

**Comment by artiebits** [comment]
great, thanks for confirming it! I've published a new version 5.5.0
