### ISSUE TITLE
Not working on Linux: Operating System Not Supported

### ISSUE THREAD

**Issue by afif-malghani** [artiebits/pdf-to-printer#440]
**Description**
When I try to print a PDF, I get the error message saying "Operating System Not Supported"

**Reproduce**

1. Boot into Ubuntu 22.04 LTS, (for me it is live from the bootable disk
2. Try Printing PDF document from node environment. I am working with electronJS
3. The error will show on the print() method call

**Expected behavior**
Should send a print command to the printer

**Comment by artiebits** [comment]
Hi @afif-malghani, I would recommend you to check the readme, you will find a solution there
