### ISSUE TITLE
More options to print a PDF

### ISSUE THREAD

**Issue by BrunoGusChagas** [artiebits/pdf-to-printer#53]
I would like to know if there is a way to set more options (not just the printer name) to the 'print' function. 

At the moment on windows, if I print a PDF manually the result is not the same if I use the 'print' function. I'm pretty sure this is related with the option 'fit to page'. 

Is there a way to include this option together with the printer name ?

**Comment by BrunoGusChagas** [comment]
UPDATE: 

I figure out that the problem was with the version of Sumatrapdf. 
Do you guys think it is possible to add a option to set executable path of sumatra. In this way, if someone needs to use a old version of it, this can be easily managed

**Comment by artiebits** [comment]
Hi @BrunoGusChagas, what version of SumatraPDF works better for you? I heard v3.0.0 prints in better quality and works with images, so I think we just can change the current version to v3.0.0. Would it help you?

**Comment by BrunoGusChagas** [comment]
Hi @artiebits, thanks for your answer ! Yes, the v3.0.0 will solve my problem.

**Comment by artiebits** [comment]
I am closing this issue because we solved it within #54
