### ISSUE TITLE
How to change A4 printing to A6

### ISSUE THREAD

**Issue by Boy-W** [artiebits/pdf-to-printer#55]
My original PDF file is A6 size, but I can only print and save it as an A4 size PDF file through your extension, forcibly changing its size. Is there any way to adjust the size of the printed PDF?

**Comment by artiebits** [comment]
Hi @Boy-W, 

Thank you for opening the issue!
To print PDF files on macOS the utility uses [lp](https://www.computerhope.com/unix/ulp.htm), and uses [SumatraPDF](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html) on Windows OS. So if you find any option that will help you to solve the problem then we can add more options to the print [method](https://github.com/artiebits/pdf-to-printer#printpdf-options--promisevoid)

**Comment by Boy-W** [comment]
> Hi @Boy-W,
> 
> Thank you for opening the issue!
> To print PDF files on macOS the utility uses [lp](https://www.computerhope.com/unix/ulp.htm), and uses [SumatraPDF](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html) on Windows OS. So if you find any option that will help you to solve the problem then we can add more options to the print [method](https://github.com/artiebits/pdf-to-printer#printpdf-options--promisevoid)

Then what if I want to use Electron to print A6 size PDF files?

**Comment by ckrgithub** [comment]
@Boy-W do you have a solution
