### ISSUE TITLE
printing from main process?

### ISSUE THREAD

**Issue by koo9** [artiebits/pdf-to-printer#57]
**To Reproduce**
calling printer.print in the main process. error message should cannot read property 'print' of undefined.

**Expected behavior**
the pdf should be printed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 78.0.3904.70

saw the react example, question is, does it has to print in the renderer process?

**Comment by koo9** [comment]
looks like just importing the printer and use it like printer.print() won't work. need to use require() to get the printer, then it works.

**Comment by artiebits** [comment]
Hi @koo9 `importing the printer and use it like printer.print() won't work` - do you mean the examples don't work for you?

**Comment by artiebits** [comment]
If you share your project with me then I can investigate the issue. 
But does import work for other packages in your project?

**Comment by koo9** [comment]
yes  it does. module like fs works fine with import

**Comment by koo9** [comment]
guess it's the different between 
 import React from 'react' vs import * as React from 'react' looks like typescript use the latter.  so changing the import statement to import * as printer from 'pdf-to-printer'; works!
