### ISSUE TITLE
Error while installing on windows

### ISSUE THREAD

**Issue by jablonskipj** [artiebits/pdf-to-printer#66]
**Describe the bug**
When I set up my project with Node.js on Windows, install the `pdf-to-printer` and try to run the application it returns an error. 

<img width="665" alt="Capture" src="https://user-images.githubusercontent.com/12045510/68525685-663fc900-02d4-11ea-800c-1f62aa727bd5.PNG">

**To Reproduce**
1. Set up the project on windows environment (with node.js)
2. Open the cmd
3. run `yarn`
4. run `yarn start`
5. See the error

**Expected behavior**
The application should start without any problems.

**Screenshots**
<img width="665" alt="Capture" src="https://user-images.githubusercontent.com/12045510/68525685-663fc900-02d4-11ea-800c-1f62aa727bd5.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
- Node.js application

**Comment by artiebits** [comment]
Hi @jablonskipj I am curious why you closed the issue. Did you manage to solve it?

**Comment by jablonskipj** [comment]
@artiebits yes. It was my mistake. I had a test execution of `print` function with hardcoded `path` to a file that was not existing on the computer that I was testing the app on :).

**Comment by artiebits** [comment]
ah, I see :)
