### ISSUE TITLE
Uncaught No such file local

### ISSUE THREAD

**Issue by lkfischer** [artiebits/pdf-to-printer#96]
Hello everyone, I have a problem where the pdf file is not found even though the path is correct.

Follows code below.

`const options = {
		    	  printer: "ELGIN-I9"
		    	};
		    	 
		    	printer
		    	  .print("req.pdf", options)
		    	  .then(console.log)
		    	  .catch(console.error);`

I am sorry for my english.

**Comment by artiebits** [comment]
Hi Lukas, is it possible to share your project with me so I can take a look? I am pretty sure the path to PDF is wrong because [I use fs.existsSync](https://github.com/artiebits/pdf-to-printer/blob/master/src/unix/print.js#L9) from [Node.js](https://nodejs.org/api/fs.html#fs_fs_existssync_path) to check the path.

**Comment by lkfischer** [comment]
I would love to pass, but unfortunately I can't because I have a confidentiality agreement. Is there any other way you can help me, because the file is in the right place even if I walk this way through a link, it can find it.

**Comment by artiebits** [comment]
btw, we have a few examples in the [examples](https://github.com/artiebits/pdf-to-printer/tree/master/examples) folder. did you have a chance to check them out to see how it works there?

**Comment by artiebits** [comment]
I've created a simple node.js project for you https://github.com/artiebits/pdf-to-printer/pull/97 it works for me on both Mac and Windows.

**Comment by artiebits** [comment]
Hi @lkfischer, did you manage to solve your issue?

**Comment by lkfischer** [comment]
Good afternoon.

I took your example and applied the path via "path", now it is working correctly.

Thank you.

**Comment by artiebits** [comment]
good to hear your issue solved!
