### ISSUE TITLE
Error: Command failed: <path to nodejs application>\node_modules\pdf-to-printer\dist\SumatraPDF.exe -print-to PRINTERNAME -silent filename.pdf

### ISSUE THREAD

**Issue by CMAX-TWOLF** [artiebits/pdf-to-printer#98]
I have been butting my head against this problem and I can't find the solution. I've uninstalled and reinstalled the package multiple times and it doesn't work, my code looks like this:

const options = {
        printer: localPrinter // local printer provided as a string of the printer name
    }

printer
        .print(customer, options)
        .then(console.log("File printed."))
        .catch(console.error)

**Comment by artiebits** [comment]
Hi @CMAX-TWOLF I have [this small example ](https://github.com/artiebits/pdf-to-printer/pull/97) which works fine for me on both Mac and Windows. Can you check it please?

**Comment by CMAX-TWOLF** [comment]
Forgive my novice understanding. I'm failing to see how the path to the PDF and printer is selected with the fix. Also, there is a list of printers on the app server to print from, but the PDF must go to a specific printer based on a value received from the app and I'm failing to see how the list selects a printer to print from.

**Comment by artiebits** [comment]
I am sorry, I don't fully understand your issue. Is it possible to create an example app with the issue? 

Are you trying to do something like this?

```javascript
const pdfToPrinter = require("pdf-to-printer");

let printer;

if (value === 1) {
  printer = 'Zebra Printer';
} 
if (value === 2) {
  printer = 'Color Lazer Printer';
}

pdfToPrinter
    .print(pdf, { printer })
    .then(console.log)
    .catch(console.error);

**Comment by artiebits** [comment]
Hi @CMAX-TWOLF did you manage to solve the issue?
