### ISSUE TITLE
Did not work inelectron production build- also please return  exception in promise

### ISSUE THREAD

**Issue by lakhvir998** [artiebits/pdf-to-printer#99]

**Comment by artiebits** [comment]
Could you share your project with me please, so I can have a look?

**Comment by lakhvir998** [comment]
Create a electron project with electron-react-boilerplate and make a production build  then test. Or i will share my code

**Comment by artiebits** [comment]
Please share your project or create an example with the issue.

**Comment by lakhvir998** [comment]
https://github.com/lakhvir998/print-app

clone this repo and try following
1. yarn dev - print will  work
2. yarn package - not working

**Comment by users23** [comment]
any update @artiebits

**Comment by artiebits** [comment]
hi @users23 not yet, i am on vacation

**Comment by users23** [comment]
its urgent we are using this for live application

**Comment by FrancescoBorzi** [comment]
@users23 this is an open source project and everyone can contribute to it. If you **urgently** need a feature/bugfix/improvement you can just open a PR and it will be reviewed and merged by the repository maintainer.

**Comment by users23** [comment]
i am unable to debug it in production

**Comment by artiebits** [comment]
Hi @users23, I am not making any money on this open-source library and working on it during my free time. I created this library to solve my task and shared it with others in case they have the same problem. I am sorry it didn't work properly for you, but I am not going to do it ASAP just because it's urgent for you.
Try to disable Asar if it's enabled, maybe it will help.

**Comment by FrancescoBorzi** [comment]
> i am unable to debug it in production

@users23 just clone this repo locally and run it in development mode, so you can do anything you want

**Comment by jaykch** [comment]
Disabling asar doesnt solve it, the above guy seems to be quite rude, enjoy your holidays man.
Looking forward to the solution, for now I am just loading the pdf as html and printing it

**Comment by dsoftware763** [comment]
> Disabling asar doesnt solve it, the above guy seems to be quite rude, enjoy your holidays man.
> Looking forward to the solution, for now I am just loading the pdf as html and printing it

can you show me how you are doing this

**Comment by jaykch** [comment]
in your

> > Disabling asar doesnt solve it, the above guy seems to be quite rude, enjoy your holidays man.
> > Looking forward to the solution, for now I am just loading the pdf as html and printing it
> 
> can you show me how you are doing this

In your package.json file under build object add "asar": false
It should give you a warning when building if you are using electron-react-boilerplate

**Comment by jaykch** [comment]
Well no one has any solution and there is no error returned for why it is not working.

**Comment by jaykch** [comment]
Any updates on this?
